### ISSUE TITLE
Getting File Error Message in MathInspector app

### ISSUE THREAD

**Issue by OrbitalMechanic** [MathInspector/MathInspector#45]
I'm attempting to run MathInspector ver. 0.9.3 (beta) on a Mac Pro (2019) under Mac OS X Big Sur (ver. 11.2.3). I'm getting the message

```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/calhoun137/Projects/TheOneThreeSeven/FourierSeries'Math Inspector UNKNOWN (Beta)
Type "help", "copyright", "credits", "license" for more information
Traceback (most recent call last):

  File "mathinspector/project.py", line 310, in load

  File "mathinspector/modules.py", line 289, in addfolder

FileNotFoundError: [Errno 2] No such file or directory: '/Users/calhoun137/Projects/TheOneThreeSeven/FourierSeries'
```

A screen-snap is attached.

Any suggestions?

Sam Dupree.

<img width="1617" alt="Screen Shot 2021-03-10 at 01 27 52" src="https://user-images.githubusercontent.com/4779511/110586777-b20cb780-8140-11eb-8f9b-93aa8bac9023.png">

**Comment by MathInspector** [comment]
Try starting a new project (File > New), then the error should go away.  Oops!  Sorry about that.  Thanks for helping to test and submitting this issue.

That error message is from one of my autosave files, and there is a big update coming out soon (hopefully within 0-3 days) which should resolve this autosave issue.  But I will take an extra close look to make sure this doesn't happen anymore.

lmk if File > New doesn't resolve it, or if you find any other issues.

**Comment by MathInspector** [comment]
Update:  I will close this issue in a few days or less, just wrapping up testing now
