### ISSUE TITLE
not able to import file into  a project

### ISSUE THREAD

**Issue by DSLituiev** [MathInspector/MathInspector#46]
When I go to `Project ->  Add File` and add a file from the same directory where I launched the `mathinspector` (pip installed), I am getting:

```
Exception in Tkinter callback
Traceback (most recent call last):

  File "/Applications/anaconda3/envs/mathinspector/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)

  File "/Applications/anaconda3/envs/mathinspector/lib/python3.8/site-packages/mathinspector/modules.py", line 231, in addfile
    if not inspect.ismodule(attr) and i in self.app.objects and i not in self.locals[name]:

KeyError: 'my_example'

```

**Comment by MathInspector** [comment]
Whoops!  Sorry about that.

I think the issue is there is a conflict with anaconda.  I can see that pip installed mathinspector in the anaconda directory.

It is my intention to have mathinspector be compatible with this use case.  At this time, anaconda python is not working properly with mathinspector, and I consider this to be a bug.

Thanks for opening this issue.  Would you mind reporting back in this thread if you find a solution that works for you?  This would be very helpful for me to gain a deeper understanding of what is going on here.

Would it be possible to use virtualenv perhaps to install mathinspector via pip without anaconda?

Alternatively, the built app on the mathinspector website contains frozen code.  However, I believe there is also a bug when anaconda python is the default and the built app is being used and you try to import a module that is in the /Applications/anaconda3/../site-packages/... folder.  Please let me know if you try this, if this is the case for you or not, as my understanding is this depends on multiple system specific factors.
