### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'Mapping'

### ISSUE THREAD

**Issue by theconsciouspasticcio** [MathInspector/MathInspector#51]
I installed the package following the instructions:
`python -m pip uninstall mathinspector`

I get this error:

```Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/user/.local/lib/python3.11/site-packages/mathinspector/__init__.py", line 68, in <module>
    from .console.interpreter import Interpreter, StdWrap
  File "/home/user/.local/lib/python3.11/site-packages/mathinspector/console/__init__.py", line 25, in <module>
    from .interpreter import Interpreter
  File "/home/user/.local/lib/python3.11/site-packages/mathinspector/console/interpreter.py", line 26, in <module>
    from ..plot import plot
  File "/home/user/.local/lib/python3.11/site-packages/mathinspector/plot/__init__.py", line 80, in <module>
    from .plot2d import SDLWindow, OPTIONS as OPTIONS_2D
  File "/home/user/.local/lib/python3.11/site-packages/mathinspector/plot/plot2d.py", line 21, in <module>
    from ..util import instanceof, hex_to_rgb
  File "/home/user/.local/lib/python3.11/site-packages/mathinspector/util/__init__.py", line 23, in <module>
    from .argspec import argspec
  File "/home/user/.local/lib/python3.11/site-packages/mathinspector/util/argspec.py", line 18, in <module>
    from .docscrape import FunctionDoc
  File "/home/user/.local/lib/python3.11/site-packages/mathinspector/util/docscrape.py", line 98, in <module>
    class NumpyDocString(collections.Mapping):
                         ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Mapping'
```
I'm using Archlinux and Python 3.11.6

**Comment by HsiangNianian** [comment]
In Python, the `collections.Mapping` abstract base class was deprecated in Python 3.3 and removed in Python 3.9.

Instead of `collections.Mapping`, you should use `collections.abc.Mapping`. `collections.abc` module provides the abstract base classes for containers in Python, and `Mapping` is one of them.

Here's how you can use it:

```python
import collections.abc

# Check if an object is a mapping (dictionary-like)
if isinstance(your_object, collections.abc.Mapping):
    # Your code here
```

This will work across different Python versions and won't raise an AttributeError.
